FROM payment-gateway1-api AS source

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=source /app/app.jar app.jar
ENV SPRING_PROFILES_ACTIVE=worker
ENTRYPOINT ["java", "-Djava.net.preferIPv4Stack=true", "-jar", "app.jar"]
