server.port=${PORT:8000}

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Jackson configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

# Redis configuration
spring.data.redis.host=${REDIS_HOST:redis}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=3000ms

# Default Test Mode parameters
gateway.test-mode=${TEST_MODE:false}
gateway.test-delay=${TEST_PROCESSING_DELAY:1000}
gateway.test-payment-success=${TEST_PAYMENT_SUCCESS:true}
gateway.test-webhook-retry=${WEBHOOK_RETRY_INTERVALS_TEST:false}
